<?php

namespace Database\Seeders;

use App\Models\Producto;
use App\Models\Categoria;
use App\Models\Subcategoria;
use App\Models\Proveedor;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener categorías y proveedores
        $categorias = Categoria::with('subcategorias')->get()->keyBy('slug');
        $proveedores = Proveedor::all();

        $productos = [
            // ALIMENTOS (ALI)
            [
                'codigo' => 'ALI-001',
                'nombre' => 'Dog Chow Adulto 22.7kg',
                'categoria' => 'alimentos',
                'subcategoria' => 'perros',
                'precio_compra' => 185000,
                'precio_venta' => 225000,
                'stock' => 15,
                'stock_minimo' => 5,
                'marca' => 'Purina',
                'presentacion' => '22.7 kg',
            ],
            [
                'codigo' => 'ALI-002',
                'nombre' => 'Cat Chow Adulto 8kg',
                'categoria' => 'alimentos',
                'subcategoria' => 'gatos',
                'precio_compra' => 95000,
                'precio_venta' => 120000,
                'stock' => 12,
                'stock_minimo' => 4,
                'marca' => 'Purina',
                'presentacion' => '8 kg',
            ],
            [
                'codigo' => 'ALI-003',
                'nombre' => 'Pedigree Adulto 17kg',
                'categoria' => 'alimentos',
                'subcategoria' => 'perros',
                'precio_compra' => 145000,
                'precio_venta' => 180000,
                'stock' => 8,
                'stock_minimo' => 4,
                'marca' => 'Pedigree',
                'presentacion' => '17 kg',
            ],
            [
                'codigo' => 'ALI-004',
                'nombre' => 'Whiskas Adulto 10kg',
                'categoria' => 'alimentos',
                'subcategoria' => 'gatos',
                'precio_compra' => 110000,
                'precio_venta' => 140000,
                'stock' => 6,
                'stock_minimo' => 3,
                'marca' => 'Whiskas',
                'presentacion' => '10 kg',
            ],
            [
                'codigo' => 'ALI-005',
                'nombre' => 'Concentrado para Aves 40kg',
                'categoria' => 'alimentos',
                'subcategoria' => 'aves',
                'precio_compra' => 85000,
                'precio_venta' => 105000,
                'stock' => 20,
                'stock_minimo' => 8,
                'marca' => 'Italcol',
                'presentacion' => '40 kg',
            ],
            [
                'codigo' => 'ALI-006',
                'nombre' => 'Alimento Peces Tropicales 100g',
                'categoria' => 'alimentos',
                'subcategoria' => 'peces',
                'precio_compra' => 12000,
                'precio_venta' => 18000,
                'stock' => 25,
                'stock_minimo' => 10,
                'marca' => 'Tetra',
                'presentacion' => '100 g',
            ],
            [
                'codigo' => 'ALI-007',
                'nombre' => 'Concentrado Equinos 40kg',
                'categoria' => 'alimentos',
                'subcategoria' => 'equinos',
                'precio_compra' => 95000,
                'precio_venta' => 120000,
                'stock' => 10,
                'stock_minimo' => 5,
                'marca' => 'Italcol',
                'presentacion' => '40 kg',
            ],

            // MEDICAMENTOS (MED)
            [
                'codigo' => 'MED-001',
                'nombre' => 'Vacuna Triple Felina',
                'categoria' => 'medicamentos',
                'subcategoria' => 'vacunas',
                'precio_compra' => 25000,
                'precio_venta' => 45000,
                'stock' => 30,
                'stock_minimo' => 10,
                'marca' => 'Zoetis',
                'presentacion' => '1 dosis',
            ],
            [
                'codigo' => 'MED-002',
                'nombre' => 'Vacuna Parvovirus Canino',
                'categoria' => 'medicamentos',
                'subcategoria' => 'vacunas',
                'precio_compra' => 18000,
                'precio_venta' => 35000,
                'stock' => 25,
                'stock_minimo' => 10,
                'marca' => 'Zoetis',
                'presentacion' => '1 dosis',
            ],
            [
                'codigo' => 'MED-003',
                'nombre' => 'Antiparasitario Canino Tableta',
                'categoria' => 'medicamentos',
                'subcategoria' => 'antiparasitarios',
                'precio_compra' => 8000,
                'precio_venta' => 15000,
                'stock' => 50,
                'stock_minimo' => 20,
                'marca' => 'Bayer',
                'presentacion' => 'Caja x 2',
            ],
            [
                'codigo' => 'MED-004',
                'nombre' => 'Ivermectina 1% 50ml',
                'categoria' => 'medicamentos',
                'subcategoria' => 'antiparasitarios',
                'precio_compra' => 22000,
                'precio_venta' => 35000,
                'stock' => 15,
                'stock_minimo' => 5,
                'marca' => 'Bayer',
                'presentacion' => '50 ml',
            ],
            [
                'codigo' => 'MED-005',
                'nombre' => 'Amoxicilina Veterinaria 100ml',
                'categoria' => 'medicamentos',
                'subcategoria' => 'antibioticos',
                'precio_compra' => 35000,
                'precio_venta' => 55000,
                'stock' => 12,
                'stock_minimo' => 5,
                'marca' => 'Zoetis',
                'presentacion' => '100 ml',
            ],
            [
                'codigo' => 'MED-006',
                'nombre' => 'Antiinflamatorio Meloxicam 20ml',
                'categoria' => 'medicamentos',
                'subcategoria' => 'antiinflamatorios',
                'precio_compra' => 42000,
                'precio_venta' => 65000,
                'stock' => 8,
                'stock_minimo' => 4,
                'marca' => 'Bayer',
                'presentacion' => '20 ml',
            ],

            // SUPLEMENTOS (SUP)
            [
                'codigo' => 'SUP-001',
                'nombre' => 'Vitaminas Caninas Completas',
                'categoria' => 'suplementos',
                'subcategoria' => 'vitaminas',
                'precio_compra' => 28000,
                'precio_venta' => 45000,
                'stock' => 20,
                'stock_minimo' => 8,
                'marca' => 'Bayer',
                'presentacion' => '60 tabletas',
            ],
            [
                'codigo' => 'SUP-002',
                'nombre' => 'Omega 3 Mascotas',
                'categoria' => 'suplementos',
                'subcategoria' => 'acidos-grasos',
                'precio_compra' => 32000,
                'precio_venta' => 50000,
                'stock' => 15,
                'stock_minimo' => 5,
                'marca' => 'Zoetis',
                'presentacion' => '120 cápsulas',
            ],
            [
                'codigo' => 'SUP-003',
                'nombre' => 'Probióticos Intestinales',
                'categoria' => 'suplementos',
                'subcategoria' => 'probioticos',
                'precio_compra' => 25000,
                'precio_venta' => 40000,
                'stock' => 18,
                'stock_minimo' => 6,
                'marca' => 'Bayer',
                'presentacion' => '30 sobres',
            ],
            [
                'codigo' => 'SUP-004',
                'nombre' => 'Calcio para Perros Grandes',
                'categoria' => 'suplementos',
                'subcategoria' => 'minerales',
                'precio_compra' => 35000,
                'precio_venta' => 55000,
                'stock' => 10,
                'stock_minimo' => 4,
                'marca' => 'Zoetis',
                'presentacion' => '90 tabletas',
            ],

            // INSUMOS AGRÍCOLAS (INS)
            [
                'codigo' => 'INS-001',
                'nombre' => 'Fertilizante NPK 10-30-10 50kg',
                'categoria' => 'insumos',
                'subcategoria' => 'fertilizantes',
                'precio_compra' => 125000,
                'precio_venta' => 160000,
                'stock' => 25,
                'stock_minimo' => 10,
                'marca' => 'Yara',
                'presentacion' => '50 kg',
            ],
            [
                'codigo' => 'INS-002',
                'nombre' => 'Urea Agrícola 50kg',
                'categoria' => 'insumos',
                'subcategoria' => 'fertilizantes',
                'precio_compra' => 95000,
                'precio_venta' => 125000,
                'stock' => 30,
                'stock_minimo' => 12,
                'marca' => 'Nutrien',
                'presentacion' => '50 kg',
            ],
            [
                'codigo' => 'INS-003',
                'nombre' => 'Herbicida Glifosato 1L',
                'categoria' => 'insumos',
                'subcategoria' => 'herbicidas',
                'precio_compra' => 28000,
                'precio_venta' => 42000,
                'stock' => 20,
                'stock_minimo' => 8,
                'marca' => 'Syngenta',
                'presentacion' => '1 litro',
            ],
            [
                'codigo' => 'INS-004',
                'nombre' => 'Insecticida Cipermetrina 1L',
                'categoria' => 'insumos',
                'subcategoria' => 'insecticidas',
                'precio_compra' => 35000,
                'precio_venta' => 52000,
                'stock' => 15,
                'stock_minimo' => 5,
                'marca' => 'Syngenta',
                'presentacion' => '1 litro',
            ],
            [
                'codigo' => 'INS-005',
                'nombre' => 'Semillas de Maíz Híbrido 20kg',
                'categoria' => 'insumos',
                'subcategoria' => 'semillas',
                'precio_compra' => 280000,
                'precio_venta' => 350000,
                'stock' => 8,
                'stock_minimo' => 3,
                'marca' => 'Syngenta',
                'presentacion' => '20 kg',
            ],
            [
                'codigo' => 'INS-006',
                'nombre' => 'Fungicida Mancozeb 1kg',
                'categoria' => 'insumos',
                'subcategoria' => 'fungicidas',
                'precio_compra' => 45000,
                'precio_venta' => 65000,
                'stock' => 12,
                'stock_minimo' => 5,
                'marca' => 'Syngenta',
                'presentacion' => '1 kg',
            ],

            // ACCESORIOS (ACC)
            [
                'codigo' => 'ACC-001',
                'nombre' => 'Collar Antipulgas Perro Grande',
                'categoria' => 'accesorios',
                'subcategoria' => 'collares',
                'precio_compra' => 35000,
                'precio_venta' => 55000,
                'stock' => 20,
                'stock_minimo' => 8,
                'marca' => 'Bayer',
                'presentacion' => 'Unidad',
            ],
            [
                'codigo' => 'ACC-002',
                'nombre' => 'Correa Retráctil 5m',
                'categoria' => 'accesorios',
                'subcategoria' => 'correas',
                'precio_compra' => 28000,
                'precio_venta' => 45000,
                'stock' => 15,
                'stock_minimo' => 5,
                'marca' => 'Flexi',
                'presentacion' => '5 metros',
            ],
            [
                'codigo' => 'ACC-003',
                'nombre' => 'Cama para Perro Mediano',
                'categoria' => 'accesorios',
                'subcategoria' => 'camas',
                'precio_compra' => 65000,
                'precio_venta' => 95000,
                'stock' => 8,
                'stock_minimo' => 3,
                'marca' => 'PetHome',
                'presentacion' => '60x80 cm',
            ],
            [
                'codigo' => 'ACC-004',
                'nombre' => 'Juguete Hueso de Goma',
                'categoria' => 'accesorios',
                'subcategoria' => 'juguetes',
                'precio_compra' => 8000,
                'precio_venta' => 15000,
                'stock' => 30,
                'stock_minimo' => 10,
                'marca' => 'Kong',
                'presentacion' => 'Mediano',
            ],
            [
                'codigo' => 'ACC-005',
                'nombre' => 'Transportadora Gato/Perro Pequeño',
                'categoria' => 'accesorios',
                'subcategoria' => 'transportadoras',
                'precio_compra' => 75000,
                'precio_venta' => 110000,
                'stock' => 6,
                'stock_minimo' => 2,
                'marca' => 'Petmate',
                'presentacion' => 'Pequeña',
            ],
            [
                'codigo' => 'ACC-006',
                'nombre' => 'Comedero Doble Acero Inox',
                'categoria' => 'accesorios',
                'subcategoria' => 'comederos',
                'precio_compra' => 22000,
                'precio_venta' => 35000,
                'stock' => 18,
                'stock_minimo' => 6,
                'marca' => 'PetBowl',
                'presentacion' => 'Grande',
            ],
            [
                'codigo' => 'ACC-007',
                'nombre' => 'Rascador para Gatos Torre',
                'categoria' => 'accesorios',
                'subcategoria' => 'rascadores',
                'precio_compra' => 85000,
                'precio_venta' => 125000,
                'stock' => 4,
                'stock_minimo' => 2,
                'marca' => 'CatTree',
                'presentacion' => '80 cm altura',
            ],
        ];

        foreach ($productos as $prodData) {
            $categoria = $categorias[$prodData['categoria']] ?? null;
            if (!$categoria) continue;

            $subcategoria = $categoria->subcategorias->firstWhere('slug', $prodData['subcategoria']);

            // Asignar un proveedor aleatorio
            $proveedor = $proveedores->random();

            Producto::updateOrCreate(
                ['codigo' => $prodData['codigo']],
                [
                    'nombre' => $prodData['nombre'],
                    'categoria_id' => $categoria->id,
                    'subcategoria_id' => $subcategoria?->id,
                    'proveedor_id' => $proveedor->id,
                    'precio_compra' => $prodData['precio_compra'],
                    'precio_venta' => $prodData['precio_venta'],
                    'stock' => $prodData['stock'],
                    'stock_minimo' => $prodData['stock_minimo'],
                    'marca' => $prodData['marca'],
                    'presentacion' => $prodData['presentacion'],
                    'unidad_medida' => 'unidad',
                    'activo' => true,
                ]
            );
        }
    }
}

